update langchain-cohere test to ensure that no new files are created

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -41,6 +41,16 @@ jobs:
           git clone https://github.com/langchain-ai/langchain-cohere.git && cd langchain-cohere/libs/cohere
           poetry install --with test 
           make test
+          echo "tests passed"
+
+          set -eu
+
+          STATUS="$(git status)"
+          echo "$STATUS"
+
+          # grep will exit non-zero if the target message isn't found,
+          # and `set -e` above will cause the step to fail.
+          echo "$STATUS" | grep 'nothing to commit, working tree clean'
         env:
           COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
   
